<?php
require_once($PrefixoIncludes.'../../conecta.php');
require_once($PrefixoIncludes.'../../functions.php');
require_once($PrefixoIncludes.'../../functions_custom.php');

require_once($PrefixoIncludes.'../../classes/class.RegistroOasis.php');
require_once($PrefixoIncludes.'../../classes/class.GeraCadCampos.php');
require_once($PrefixoIncludes.'../../classes/class.GeraCadPost.php');
require_once($PrefixoIncludes.'../../classes/class.Usuario.php');
require_once($PrefixoIncludes.'../../classes/class.Pessoa.php');
require_once($PrefixoIncludes.'../../classes/class.Produto.php');
require_once($PrefixoIncludes.'../../classes/class.uM.php');
require_once($PrefixoIncludes.'../../classes/class.uB.php');
require_once($PrefixoIncludes.'../../classes/class.Url.php');
require_once($PrefixoIncludes.'../../classes/class.ConsultaEstoque.php');
require_once($PrefixoIncludes.'../../classes/class.ConsultaEstoqueCustom.php');
require_once($PrefixoIncludes.'../../classes/class.ConsultaEstoqueXMLErpDatasul.php');
require_once($PrefixoIncludes.'../../classes/class.SubstituicaoTributaria.php');
require_once($PrefixoIncludes.'../../classes/class.CFOP.php');
require_once($PrefixoIncludes.'../../classes/class.UF.php');
require_once($PrefixoIncludes.'../../classes/class.ICMS.php');
require_once($PrefixoIncludes.'../../classes/class.IPI.php');
require_once($PrefixoIncludes.'../../classes/class.SugestaoCFOP.php');
require_once($PrefixoIncludes.'../../classes/class.SugestaoCFOPCustom.php');
require_once($PrefixoIncludes.'../../classes/class.Contato.php');
require_once($PrefixoIncludes.'../../classes/class.Oportunidade.php');
require_once($PrefixoIncludes.'../../classes/class.Atividade.php');
require_once($PrefixoIncludes.'../../classes/class.phpmailer.php');
require_once($PrefixoIncludes.'../../classes/class.Email.php');
require_once($PrefixoIncludes.'../../classes/class.Estabelecimento.php');
require_once($PrefixoIncludes.'../../classes/class.PessoaEndereco.php');
require_once($PrefixoIncludes.'../../classes/class.Transportadora.php');
require_once($PrefixoIncludes.'../../classes/class.DataHora.php');
require_once($PrefixoIncludes.'../../classes/class.ControleAcesso.php');

require_once($PrefixoIncludes.'classes/class.Venda.php');
require_once($PrefixoIncludes.'classes/class.Venda.Orcamento.php');
require_once($PrefixoIncludes.'classes/class.Venda.Pedido.php');
require_once($PrefixoIncludes.'classes/class.Venda.Frete.php');
require_once($PrefixoIncludes.'classes/class.Venda.Frete.Custom.php');
require_once($PrefixoIncludes.'classes/class.Venda.Kit.php');
require_once($PrefixoIncludes.'classes/class.Venda.Item.php');
require_once($PrefixoIncludes.'classes/class.Venda.Item.Comissao.php');
require_once($PrefixoIncludes.'classes/class.Venda.Representante.php');
require_once($PrefixoIncludes.'classes/class.Venda.Campos.php');
require_once($PrefixoIncludes.'classes/class.Venda.CamposCustom.php');
require_once($PrefixoIncludes.'classes/class.Venda.Parametro.php');
require_once($PrefixoIncludes.'classes/class.Venda.AprovacaoComercial.php');
require_once($PrefixoIncludes.'classes/class.VendaCallBackCustom.php');
require_once($PrefixoIncludes.'classes/class.Venda.Customizacoes.php');
require_once($PrefixoIncludes.'classes/class.Venda.CustomizacoesCustom.php');

require_once($PrefixoIncludes.'classes/class.PoliticaComercialDescVendaMedia.php');
require_once($PrefixoIncludes.'classes/class.PoliticaComercialDescVendaCampoDescontoFixo.php');

require_once($PrefixoIncludes.'classes/class.PoliticaComercialDescVendaItemMedia.php');
require_once($PrefixoIncludes.'classes/class.PoliticaComercialDescVendaItemCampoDescontoFixo.php');
require_once($PrefixoIncludes.'classes/class.PoliticaComercialDescVendaItemCampoDesconto.php');

require_once($PrefixoIncludes.'classes/class.Venda.Bonificacao.php');
require_once($PrefixoIncludes.'classes/class.PoliticaComercialComis.php');
require_once($PrefixoIncludes.'classes/class.Preco.Produto.php');
require_once($PrefixoIncludes.'classes/class.PoliticaComercialBloqueioFinalizacao.php');
require_once($PrefixoIncludes.'classes/class.Venda.CondicaoPagamentoProgramado.php');

require_once($PrefixoIncludes.'../integracao_datasul/class.VendaExpODBC.php');
require_once($PrefixoIncludes.'../integracao_datasul/class.VendaExpODBCCustom.php');
require_once('includes_custom.php');
?>